[package]
name = "rpfm_macros"
version = "2.3.100"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
description = "Library with some custom macros used in RPFM."
edition = "2018"

[lib]
proc-macro=true

[dependencies]
quote = "^1.0"
syn = "^1.0"
